### ISSUE TITLE
FE: Signup / Login front-end

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-mango#7]
- create two front-end react routers (login and signup)
- There is no landing page - redirect to signup
- Signup page - name, email, password + confirm password
- Ignore Forget password (we don't need that right now)
- Front-end validation as well:
     - Examples: Password length >= 6, All fields are required, email is properly formatted (if you wrap signup and login in an HTML form, you can leverage some front-end HTML form validation, required and right typing)
     - leverage error, helperText, and snackbars (material-ui) for showing validation errors, https://material-ui.com/components/snackbars/ + https://material-ui.com/components/text-fields/

**Comment by samsoncsyu7777** [comment]
The UI of both sign up and login pages are developed completely. I will pull the dev and test the fetching after issue #6 is merged into the dev.

**Comment by samsoncsyu7777** [comment]
Responsive layout:

https://www.telerik.com/blogs/creating-a-responsive-layout-in-react#:~:text=Learn%20the%20basic%20steps%20to,help%20you%20layout%20your%20site.
