### ISSUE TITLE
FS: Tell Me About Yourself Page

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-mango#8]
- Work on the tell us about your background page
- Language dropdown (programming languages dropdown, not spoken language)
- Experience counter 
- Rating your skill set
- Add a back-end API to edit the user and save these details on the user

**Comment by samsoncsyu7777** [comment]
https://material-ui.com/components/selects/
Material-UI select component

**Comment by samsoncsyu7777** [comment]
experience: Less than 1 year/ 1 to 3 years/ 4 to 6 years/ 7 to 10 years/  More than 10 years

**Comment by samsoncsyu7777** [comment]
https://material-ui.com/components/rating/
Material-UI five stars rating with hover-feedback

**Comment by samsoncsyu7777** [comment]
five rating:
junior,
advanced junior,
intermediate,
senior,
advanced senior
